title: Oblivious Inc.
description: The adventures of four hapless Midwestern ghost hunters.
theme: jekyll-theme-merlot
show_links: true
links:
  home_url: https://obliviousinc.github.io
  playlist_url: https://www.youtube.com/playlist?list=PLElpeD07ZF8zov__m_c46Eft1CssE6Kig
  youtube_url: https://www.youtube.com/c/obliviousfilms
  twitch_url: https://www.twitch.tv/obliviousfilms
collections:
  - posts