title: Oblivious Inc.
description: Following the adventures of four hapless ghost hunters.
theme: jekyll-theme-merlot
show_links: true
links:
  home_url: https://obliviousinc.github.io
  youtube_url: https://www.youtube.com/watch?v=llktaUTbWaE&list=PLElpeD07ZF8zov__m_c46Eft1CssE6Kig
  channel_url: https://www.youtube.com/c/obliviousfilms
